### ISSUE TITLE
How do you port your fnf mods? i need help im on chromebook my widows isnt working at the moment

### ISSUE THREAD

**Issue by LEVIXDDLMAO** [SuperTeamXP/FNF-DUSTTALE-Web-High-End-Device#3]

**Comment by SuperTeamXP** [comment]
I don’t really know how to port/compile source code on Chromebook since I don’t use it, but I basically download the source code for the mod and then depending on if it’s kade engine or psych engine I follow the instructions on how to build the engine and what programs need to be installed at that engine’s GitHub page, then I compile the source code to html5 using command prompt. This most likely doesn’t work on Chromebook and if it does, it’s probably harder to figure out how to install the Windows applications on Chromebook and compile the source code, and even on Windows it can sometimes be hard because you will sometimes encounter errors when building for html5 that you have to fix. But that’s basically how I port the mods
